### ISSUE TITLE
hello i have a question for you 

### ISSUE THREAD

**Issue by hexiangquan** [mvirgo/Finding-Lane-Lines#1]
https://www.youtube.com/watch?v=ZZAgcSqAU0I 
is your prj, how to detect lane use deep learn or use a,b,c value for train ?

**Comment by mvirgo** [comment]
That uses deep learning, although what I am doing for training is feeding the six polynomial coefficients (three for each line in ax^2+bx+c) that were created using a computer vision-based model. Does that make sense?

**Comment by hexiangquan** [comment]
certianly i doing training .too .but  train dataset  is small .can you  share your dataset ?

**Comment by mvirgo** [comment]
I am still thinking of the best way to make the dataset more robust - most likely using road images from multiple different cameras (so the model can generalize through multiple image distortions of the road). Once I get comfortable with it I am definitely open to sharing it with you.

**Comment by hexiangquan** [comment]
i agree with you. i also encounter this problem

发自我的 iPhone

**Comment by hexiangquan** [comment]
any progress you have get ?  can we exchange dataset ？

**Comment by mvirgo** [comment]
Looks like you've found it anyway, but my MLND-Capstone repo has training images as well as a 'G' channel of the lane detection as labels. Let me know if you'd like me to send you the data that is the polynomial coefficients of the lines (six for each image) as well.

**Comment by hexiangquan** [comment]
no problem 

发自我的 iPhone
