### ISSUE TITLE
Code isnt working 

### ISSUE THREAD

**Issue by Neha-swan** [mvirgo/Finding-Lane-Lines#2]
Hey this code doesnt work for following video
it says -- 'NoneType' object is not iterable
 
can you resolve ? 
![1](https://user-images.githubusercontent.com/20682467/38947289-c9398c58-4359-11e8-8efb-f7885ca7dd86.jpg)

**Comment by mvirgo** [comment]
It would only show `NoneType` if it wasn't able to find the lines - since this is the pretty basic and naive first project of SDCND, it probably would need much more specific tuning to work with an image like this where the line colors are a bit off-white (due to rain and such).
